//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int FormID { get; set; }
        public string Email { get; set; }
        public string CheckIn { get; set; }
        public string CheckOut { get; set; }
        public string OwnerName { get; set; }
        public string PhoneNumber { get; set; }
        public string CatsName { get; set; }
        public int CatsNum { get; set; }
        public string RoomName { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
