//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomSize { get; set; }
        public string CatsLimit { get; set; }
        public string SunTime { get; set; }
        public string OverTime { get; set; }
        public string AddCats { get; set; }
        public string Price { get; set; }
        public string RoomImg { get; set; }
        public string RoomImgg { get; set; }
        public string RoomImggg { get; set; }
        public string RoomDesc { get; set; }
        public int Type { get; set; }
    }
}
